### ISSUE TITLE
Wrist Servo may increment from wrong position

### ISSUE THREAD

**Issue by TrisDooley** [technototes/IntoTheDeep2024#52]
In HorizontalSlidesSubsystem, the function `setWristPos` is not used for all movements. This could lead to the servo moving to unintended positions when using the Increment and Decrement commands. 

Example: `ClawWristServoTransfer` is called, moving the servo to a position of 0.3. Next, the increment command is called, which moves the servo to `wristTargetPos + WristServoIncrement`, which might evaluate to a position of 0.555, actually moving the servo down.

**Comment by kevinfrei** [comment]
Fixed by Braelyn over the weekend
